-- GENERATED by scripts/build-rehearsal-migration.mjs. Do not hand-edit.
-- Root companion rehearsal only. Legacy migration 001 is intentionally excluded.
-- Atomic, one-time install: never refresh live credentials or copy live activity.
begin;
do $guard$ begin
 if exists(select 1 from pg_catalog.pg_class c join pg_catalog.pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and (c.relname like 'rehearsal\_ops\_%' escape '\' or c.relname like 'rehearsal\_community\_v2%' escape '\'))
 or exists(select 1 from pg_catalog.pg_proc p join pg_catalog.pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and (p.proname like 'rehearsal\_ops\_%' escape '\' or p.proname like 'rehearsal\_community\_v2%' escape '\'))
 or exists(select 1 from storage.buckets where id='rehearsal-community-photos-v2') then
  raise exception 'rehearsal already exists; refusing non-reentrant install';
 end if;
end; $guard$;

-- Replay 002_team_operations.sql

-- Isolated from the pilot tables in 001. Only the server's service-role key may call these RPCs.
create table public.rehearsal_ops_accounts (
  username text primary key check (username = upper(username) and username ~ '^[A-Z0-9_-]{1,80}$'),
  role text not null check (role in ('superadmin', 'parking', 'space')),
  display_label text not null check (char_length(display_label) between 1 and 30),
  password_hash text check (password_hash is null or password_hash ~ '^scrypt\$[0-9a-f]{32}\$[0-9a-f]{64}$'),
  active boolean not null default false,
  credential_version integer not null default 1 check (credential_version > 0),
  failed_attempts integer not null default 0 check (failed_attempts >= 0),
  failed_window_started_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create table public.rehearsal_ops_sessions (
  id uuid primary key default gen_random_uuid(),
  username text not null references public.rehearsal_ops_accounts(username) on delete cascade,
  credential_version integer not null,
  display_name text not null check (char_length(display_name) between 1 and 30), -- self-reported, not verified identity
  label text not null unique check (label ~ '^S-[A-F0-9]{10}$'),
  expires_at timestamptz not null,
  revoked_at timestamptz,
  created_at timestamptz not null default now()
);
create index rehearsal_ops_sessions_active_lookup on public.rehearsal_ops_sessions (id, username, expires_at) where revoked_at is null;
create table public.rehearsal_ops_resources (
  id text primary key,
  label text not null,
  category text not null check (category in ('parking', 'space')),
  state text not null,
  version integer not null default 0 check (version >= 0),
  updated_at timestamptz,
  check ((id = 'space.songrim.access' and state in ('checking','closed','school_open','gym_open','hall_open','hall_closed')) or (id <> 'space.songrim.access' and state in ('checking','closed','available','busy','full')))
);
create table public.rehearsal_ops_history (
  id uuid primary key default gen_random_uuid(),
  resource_id text not null references public.rehearsal_ops_resources(id),
  before_state text not null,
  after_state text not null,
  actor_username text not null references public.rehearsal_ops_accounts(username),
  actor_label text not null, -- session self-reported label, deliberately not an identity claim
  session_label text not null,
  created_at timestamptz not null default now()
);
create index rehearsal_ops_history_recent on public.rehearsal_ops_history (created_at desc);
create table public.rehearsal_ops_request_receipts (
  request_id uuid primary key,
  session_id uuid not null references public.rehearsal_ops_sessions(id),
  resource_id text not null,
  state text not null,
  expected_version integer not null,
  result jsonb not null,
  created_at timestamptz not null default now()
);

alter table public.rehearsal_ops_accounts enable row level security;
alter table public.rehearsal_ops_sessions enable row level security;
alter table public.rehearsal_ops_resources enable row level security;
alter table public.rehearsal_ops_history enable row level security;
alter table public.rehearsal_ops_request_receipts enable row level security;
revoke all on table public.rehearsal_ops_accounts, public.rehearsal_ops_sessions, public.rehearsal_ops_resources, public.rehearsal_ops_history, public.rehearsal_ops_request_receipts from public, anon, authenticated;

create or replace function public.rehearsal_ops_bootstrap_superadmin(p_username text, p_password_hash text)
returns void language plpgsql security definer set search_path = '' as $$
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
  -- Serialize first-install bootstrap so two first logins cannot race.
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal_ops_bootstrap_superadmin', 0));
  -- Bootstrap only an empty installation. Existing DB accounts are canonical thereafter, so stale bootstrap env values are ignored.
  if exists (select 1 from public.rehearsal_ops_accounts where role = 'superadmin') then return; end if;
  if p_username is null or p_password_hash is null or p_username !~ '^[A-Z0-9_-]{1,80}$' or p_password_hash !~ '^scrypt\$[0-9a-f]{32}\$[0-9a-f]{64}$' then raise exception 'invalid bootstrap'; end if;
  insert into public.rehearsal_ops_accounts(username, role, display_label, password_hash, active) values (p_username, 'superadmin', '관리자', p_password_hash, true)
  on conflict (username) do nothing;
end; $$;
create or replace function public.rehearsal_ops_reserve_login(p_username text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare a public.rehearsal_ops_accounts%rowtype; v_now timestamptz := pg_catalog.now(); v_retry integer;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
  select * into a from public.rehearsal_ops_accounts where username = p_username for update;
  if not found or not a.active or a.password_hash is null then return jsonb_build_object('status','invalid'); end if;
  if a.failed_window_started_at is not null and a.failed_window_started_at > v_now - interval '15 minutes' and a.failed_attempts >= 12 then
    v_retry := greatest(1, ceil(extract(epoch from (a.failed_window_started_at + interval '15 minutes' - v_now)))::integer);
    return jsonb_build_object('status','limited','retryAfter',v_retry);
  end if;
  if a.failed_window_started_at is null or a.failed_window_started_at <= v_now - interval '15 minutes' then
    update public.rehearsal_ops_accounts set failed_attempts = 1, failed_window_started_at = v_now, updated_at = v_now where username = p_username;
  else
    update public.rehearsal_ops_accounts set failed_attempts = failed_attempts + 1, updated_at = v_now where username = p_username;
  end if;
  return jsonb_build_object('status','reserved','passwordHash',a.password_hash,'credentialVersion',a.credential_version);
end; $$;
create or replace function public.rehearsal_ops_finish_login(p_username text, p_success boolean, p_display_name text default null, p_session_label text default null, p_expires_at timestamptz default null, p_expected_credential_version integer default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare a public.rehearsal_ops_accounts%rowtype; s public.rehearsal_ops_sessions%rowtype;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
  select * into a from public.rehearsal_ops_accounts where username = p_username for update;
  if not found or not a.active or a.password_hash is null then raise exception 'invalid login'; end if;
  if p_expected_credential_version is distinct from a.credential_version then raise exception 'stale credentials' using errcode='40001'; end if;
  if not p_success then return jsonb_build_object('ok',false); end if;
  if p_display_name is null or char_length(p_display_name) not between 1 and 30 or p_session_label !~ '^S-[A-F0-9]{10}$' or p_expires_at is null then raise exception 'invalid login completion'; end if;
  update public.rehearsal_ops_accounts set failed_attempts = 0, failed_window_started_at = null, updated_at = now() where username = p_username;
  insert into public.rehearsal_ops_sessions(username, credential_version, display_name, label, expires_at) values (a.username, a.credential_version, p_display_name, p_session_label, p_expires_at) returning * into s;
  return jsonb_build_object('id',s.id,'username',a.username,'role',a.role,'credentialVersion',a.credential_version,'label',s.label);
end; $$;
create or replace function public.rehearsal_ops_get_session(p_session_id uuid)
returns jsonb language sql stable security definer set search_path = '' as $$
  select jsonb_build_object('username',a.username,'role',a.role,'credentialVersion',a.credential_version,'displayName',s.display_name,'label',s.label)
  from public.rehearsal_ops_sessions s join public.rehearsal_ops_accounts a on a.username=s.username
  where s.id=p_session_id and s.revoked_at is null and s.expires_at > now() and a.active and a.credential_version=s.credential_version;
$$;
create or replace function public.rehearsal_ops_revoke_session(p_session_id uuid)
returns void language sql security definer set search_path = '' as $$ update public.rehearsal_ops_sessions set revoked_at=now() where id=p_session_id and revoked_at is null; $$;
create or replace function public.rehearsal_ops_list_operations(p_session_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
 select a.role into v_role from public.rehearsal_ops_sessions s join public.rehearsal_ops_accounts a on a.username=s.username where s.id=p_session_id and s.revoked_at is null and s.expires_at>now() and a.active and a.credential_version=s.credential_version;
 if v_role is null then raise exception 'unauthorized' using errcode='42501'; end if;
 return jsonb_build_object('resources', (select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'label',r.label,'category',r.category,'state',r.state,'version',r.version,'updatedAt',r.updated_at) order by r.id),'[]'::jsonb) from public.rehearsal_ops_resources r where v_role='superadmin' or r.category=v_role), 'history', (select coalesce(jsonb_agg(jsonb_build_object('id',recent.id,'resourceId',recent.resource_id,'beforeState',recent.before_state,'afterState',recent.after_state,'actorUsername',recent.actor_username,'actorLabel',recent.actor_label,'sessionLabel',recent.session_label,'createdAt',recent.created_at) order by recent.created_at desc),'[]'::jsonb) from (select h.* from public.rehearsal_ops_history h join public.rehearsal_ops_resources r on r.id=h.resource_id where v_role='superadmin' or r.category=v_role order by h.created_at desc limit 100) recent), 'canManageAccounts',v_role='superadmin');
end; $$;
create or replace function public.rehearsal_ops_set_resource_state(p_session_id uuid, p_resource_id text, p_state text, p_expected_version integer, p_request_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; v_user text; v_label text; v_session_label text; r public.rehearsal_ops_resources%rowtype; old public.rehearsal_ops_request_receipts%rowtype; result jsonb; v_before text;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
 -- Serialize a request ID before checking/inserting its receipt, so concurrent retries replay rather than race into a duplicate audit row.
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-request:' || p_request_id::text, 0));
 select a.role,a.username,s.display_name,s.label into v_role,v_user,v_label,v_session_label from public.rehearsal_ops_sessions s join public.rehearsal_ops_accounts a on a.username=s.username where s.id=p_session_id and s.revoked_at is null and s.expires_at>now() and a.active and a.credential_version=s.credential_version for update of s,a;
 if v_role is null then raise exception 'unauthorized' using errcode='42501'; end if;
 select * into old from public.rehearsal_ops_request_receipts where request_id=p_request_id;
 if found then
   if old.session_id<>p_session_id or old.resource_id<>p_resource_id or old.state<>p_state or old.expected_version<>p_expected_version then return jsonb_build_object('status','payload_mismatch'); end if;
   return old.result;
 end if;
 select * into r from public.rehearsal_ops_resources where id=p_resource_id for update;
 if not found or (v_role <> 'superadmin' and r.category <> v_role) then raise exception 'unauthorized' using errcode='42501'; end if;
 if (r.id='space.songrim.access' and p_state not in ('checking','closed','school_open','gym_open','hall_open','hall_closed')) or (r.id<>'space.songrim.access' and p_state not in ('checking','closed','available','busy','full')) then raise exception 'invalid state'; end if;
 if r.version<>p_expected_version then
   result:=jsonb_build_object('status','conflict','resource',jsonb_build_object('id',r.id,'label',r.label,'category',r.category,'state',r.state,'version',r.version,'updatedAt',r.updated_at));
 else
   v_before:=r.state;
   update public.rehearsal_ops_resources set state=p_state,version=version+1,updated_at=now() where id=r.id returning * into r;
   insert into public.rehearsal_ops_history(resource_id,before_state,after_state,actor_username,actor_label,session_label) values(r.id,v_before,p_state,v_user,v_label,v_session_label);
   result:=jsonb_build_object('status','ok','resource',jsonb_build_object('id',r.id,'label',r.label,'category',r.category,'state',r.state,'version',r.version,'updatedAt',r.updated_at));
 end if;
 insert into public.rehearsal_ops_request_receipts(request_id,session_id,resource_id,state,expected_version,result) values(p_request_id,p_session_id,p_resource_id,p_state,p_expected_version,result);
 return result;
end; $$;
create or replace function public.rehearsal_ops_list_accounts(p_session_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
 select a.role into v_role from public.rehearsal_ops_sessions s join public.rehearsal_ops_accounts a on a.username=s.username where s.id=p_session_id and s.revoked_at is null and s.expires_at>now() and a.active and a.credential_version=s.credential_version;
 if v_role is distinct from 'superadmin' then raise exception 'unauthorized' using errcode='42501'; end if;
 return (select coalesce(jsonb_agg(jsonb_build_object('username',username,'role',role,'displayLabel',display_label,'active',active,'hasPassword',password_hash is not null) order by username),'[]'::jsonb) from public.rehearsal_ops_accounts);
end; $$;
create or replace function public.rehearsal_ops_upsert_account(p_session_id uuid, p_username text, p_role text, p_display_label text, p_password_hash text, p_active boolean)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text; a public.rehearsal_ops_accounts%rowtype; v_revoke boolean;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
 select actor.role into v_role from public.rehearsal_ops_sessions s join public.rehearsal_ops_accounts actor on actor.username=s.username where s.id=p_session_id and s.revoked_at is null and s.expires_at>now() and actor.active and actor.credential_version=s.credential_version for update of s,actor;
 if v_role is distinct from 'superadmin' then raise exception 'unauthorized' using errcode='42501'; end if;
 if p_username !~ '^[A-Z0-9_-]{1,80}$' or p_role not in ('parking','space') or char_length(p_display_label) not between 1 and 30 or (p_password_hash is not null and p_password_hash !~ '^scrypt\$[0-9a-f]{32}\$[0-9a-f]{64}$') then raise exception 'invalid account'; end if;
 select * into a from public.rehearsal_ops_accounts where username=p_username for update;
 if not found then
   if p_active and p_password_hash is null then raise exception 'active account requires password'; end if;
   insert into public.rehearsal_ops_accounts(username,role,display_label,password_hash,active) values(p_username,p_role,p_display_label,p_password_hash,p_active) returning * into a;
 else
   if a.role = 'superadmin' then raise exception 'superadmin account is immutable here' using errcode='42501'; end if;
   if p_active and coalesce(p_password_hash,a.password_hash) is null then raise exception 'active account requires password'; end if;
   v_revoke := p_password_hash is not null or a.active<>p_active or a.role<>p_role;
   update public.rehearsal_ops_accounts set role=p_role,display_label=p_display_label,password_hash=coalesce(p_password_hash,password_hash),active=p_active,credential_version=case when v_revoke then credential_version+1 else credential_version end,failed_attempts=case when p_password_hash is not null or (not a.active and p_active) then 0 else failed_attempts end,failed_window_started_at=case when p_password_hash is not null or (not a.active and p_active) then null else failed_window_started_at end,updated_at=now() where username=p_username returning * into a;
   if v_revoke then update public.rehearsal_ops_sessions set revoked_at=now() where username=p_username and revoked_at is null; end if;
 end if;
 return jsonb_build_object('username',a.username,'role',a.role,'displayLabel',a.display_label,'active',a.active,'hasPassword',a.password_hash is not null);
end; $$;
create or replace function public.rehearsal_ops_public_resources()
returns jsonb language sql stable security definer set search_path = '' as $$
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'label',label,'category',category,'state',state,'version',version,'updatedAt',updated_at) order by id),'[]'::jsonb) from public.rehearsal_ops_resources;
$$;

-- No browser role gets table or function access. The Vercel server uses SUPABASE_SERVICE_ROLE_KEY.
revoke all on function public.rehearsal_ops_bootstrap_superadmin(text,text), public.rehearsal_ops_reserve_login(text), public.rehearsal_ops_finish_login(text,boolean,text,text,timestamptz,integer), public.rehearsal_ops_get_session(uuid), public.rehearsal_ops_revoke_session(uuid), public.rehearsal_ops_list_operations(uuid), public.rehearsal_ops_set_resource_state(uuid,text,text,integer,uuid), public.rehearsal_ops_list_accounts(uuid), public.rehearsal_ops_upsert_account(uuid,text,text,text,text,boolean), public.rehearsal_ops_public_resources() from public, anon, authenticated;
grant execute on function public.rehearsal_ops_bootstrap_superadmin(text,text), public.rehearsal_ops_reserve_login(text), public.rehearsal_ops_finish_login(text,boolean,text,text,timestamptz,integer), public.rehearsal_ops_get_session(uuid), public.rehearsal_ops_revoke_session(uuid), public.rehearsal_ops_list_operations(uuid), public.rehearsal_ops_set_resource_state(uuid,text,text,integer,uuid), public.rehearsal_ops_list_accounts(uuid), public.rehearsal_ops_upsert_account(uuid,text,text,text,text,boolean), public.rehearsal_ops_public_resources() to service_role;

insert into public.rehearsal_ops_resources(id,label,category,state) values
 ('parking.songrim','송림본당 주차','parking','checking'),
 ('parking.dream.b1','드림센터 B1','parking','checking'),('parking.dream.b2','드림센터 B2','parking','checking'),('parking.dream.b3','드림센터 B3','parking','checking'),('parking.dream.b4','드림센터 B4','parking','checking'),('parking.dream.b5','드림센터 B5','parking','checking'),
 ('space.songrim.access','송림본당 개방 단계','space','checking'),('space.songrim.hall','본당1·2층','space','checking'),('space.songrim.gym','체육관','space','checking'),('space.dream.f3','드림센터 3층','space','checking'),('space.dream.f7','드림센터 7층','space','checking'),('space.dream.f11','드림센터 11층','space','checking')
on conflict (id) do nothing;


-- Replay 003_review_hardening.sql

-- 002 is already applied. Reservation rows make a successful login refund only its own reserved attempt.
create table if not exists public.rehearsal_ops_login_reservations (
  id uuid primary key default gen_random_uuid(),
  username text not null references public.rehearsal_ops_accounts(username) on delete cascade,
  credential_version integer not null,
  window_started_at timestamptz not null,
  consumed_at timestamptz,
  created_at timestamptz not null default now()
);
create index if not exists rehearsal_ops_login_reservations_account on public.rehearsal_ops_login_reservations(username, created_at);
alter table public.rehearsal_ops_login_reservations enable row level security;
revoke all on table public.rehearsal_ops_login_reservations from public, anon, authenticated;

-- 002 exposed this signature. Replace it rather than retaining a path without reservation binding.
revoke all on function public.rehearsal_ops_finish_login(text,boolean,text,text,timestamptz,integer) from public, anon, authenticated, service_role;
drop function public.rehearsal_ops_finish_login(text,boolean,text,text,timestamptz,integer);

create or replace function public.rehearsal_ops_reserve_login(p_username text)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare account_row public.rehearsal_ops_accounts%rowtype; v_now timestamptz := pg_catalog.now(); v_window timestamptz; v_reservation uuid; v_retry integer;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
  -- All functions that lock an account/session take this username key first.
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-ops-account:' || coalesce(p_username, ''), 0));
  select * into account_row from public.rehearsal_ops_accounts where username = p_username for update;
  if not found or not account_row.active or account_row.password_hash is null then return jsonb_build_object('status','invalid'); end if;
  if account_row.failed_window_started_at is not null and account_row.failed_window_started_at > v_now - interval '15 minutes' and account_row.failed_attempts >= 12 then
    v_retry := greatest(1, ceil(extract(epoch from (account_row.failed_window_started_at + interval '15 minutes' - v_now)))::integer);
    return jsonb_build_object('status','limited','retryAfter',v_retry);
  end if;
  if account_row.failed_window_started_at is null or account_row.failed_window_started_at <= v_now - interval '15 minutes' then
    v_window := v_now;
    update public.rehearsal_ops_accounts set failed_attempts=1,failed_window_started_at=v_window,updated_at=v_now where username=p_username;
  else
    v_window := account_row.failed_window_started_at;
    update public.rehearsal_ops_accounts set failed_attempts=failed_attempts+1,updated_at=v_now where username=p_username;
  end if;
  insert into public.rehearsal_ops_login_reservations(username,credential_version,window_started_at) values(p_username,account_row.credential_version,v_window) returning id into v_reservation;
  return jsonb_build_object('status','reserved','passwordHash',account_row.password_hash,'credentialVersion',account_row.credential_version,'reservationId',v_reservation);
end; $$;

create function public.rehearsal_ops_finish_login(p_username text, p_reservation_id uuid, p_success boolean, p_display_name text default null, p_session_label text default null, p_expires_at timestamptz default null, p_expected_credential_version integer default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare account_row public.rehearsal_ops_accounts%rowtype; reservation_row public.rehearsal_ops_login_reservations%rowtype; session_row public.rehearsal_ops_sessions%rowtype; v_account_found boolean; v_reservation_found boolean; v_now timestamptz := pg_catalog.now();
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-ops-account:' || coalesce(p_username, ''), 0));
  select * into account_row from public.rehearsal_ops_accounts where username=p_username for update;
  v_account_found := found;
  select * into reservation_row from public.rehearsal_ops_login_reservations where id=p_reservation_id for update;
  v_reservation_found := found;
  if not v_reservation_found or reservation_row.username is distinct from p_username or reservation_row.consumed_at is not null then return jsonb_build_object('status','stale'); end if;
  -- A reservation is single-use even when a credential reset made it stale.
  update public.rehearsal_ops_login_reservations set consumed_at=v_now where id=reservation_row.id and consumed_at is null;
  if not v_account_found or not account_row.active or account_row.password_hash is null or reservation_row.credential_version is distinct from p_expected_credential_version or reservation_row.credential_version is distinct from account_row.credential_version then return jsonb_build_object('status','stale'); end if;
  if not p_success then return jsonb_build_object('status','failed'); end if;
  if p_display_name is null or char_length(p_display_name) not between 1 and 30 or p_session_label !~ '^S-[A-F0-9]{10}$' or p_expires_at is null then raise exception 'invalid login completion'; end if;
  -- Refund precisely this reservation only if it belongs to the still-current window. Never clear other attempts.
  if account_row.failed_window_started_at = reservation_row.window_started_at and account_row.failed_window_started_at > v_now - interval '15 minutes' and account_row.failed_attempts > 0 then
    update public.rehearsal_ops_accounts set failed_attempts=failed_attempts-1,updated_at=v_now where username=p_username;
  end if;
  insert into public.rehearsal_ops_sessions(username,credential_version,display_name,label,expires_at) values(account_row.username,account_row.credential_version,p_display_name,p_session_label,p_expires_at) returning * into session_row;
  return jsonb_build_object('id',session_row.id,'username',account_row.username,'role',account_row.role,'credentialVersion',account_row.credential_version,'label',session_row.label);
end; $$;

create or replace function public.rehearsal_ops_get_session(p_session_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_username text; result jsonb;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
  select username into v_username from public.rehearsal_ops_sessions where id=p_session_id;
  if v_username is null then return null; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-ops-account:' || v_username, 0));
  select jsonb_build_object('username',actor.username,'role',actor.role,'credentialVersion',actor.credential_version,'displayName',session_row.display_name,'label',session_row.label) into result
  from public.rehearsal_ops_sessions session_row join public.rehearsal_ops_accounts actor on actor.username=session_row.username
  where session_row.id=p_session_id and session_row.revoked_at is null and session_row.expires_at>now() and actor.active and actor.credential_version=session_row.credential_version;
  return result;
end; $$;

create or replace function public.rehearsal_ops_revoke_session(p_session_id uuid)
returns void language plpgsql security definer set search_path = '' as $$
declare v_username text;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
  select username into v_username from public.rehearsal_ops_sessions where id=p_session_id;
  if v_username is null then return; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-ops-account:' || v_username, 0));
  update public.rehearsal_ops_sessions set revoked_at=now() where id=p_session_id and username=v_username and revoked_at is null;
end; $$;

create or replace function public.rehearsal_ops_set_resource_state(p_session_id uuid, p_resource_id text, p_state text, p_expected_version integer, p_request_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_session_username text; v_role text; v_user text; v_label text; v_session_label text; resource_row public.rehearsal_ops_resources%rowtype; old_receipt public.rehearsal_ops_request_receipts%rowtype; result jsonb; v_before text;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
  -- Read username without a row lock, acquire its advisory lock, then reauthorize under row locks.
  select username into v_session_username from public.rehearsal_ops_sessions where id=p_session_id;
  if v_session_username is null then raise exception 'unauthorized' using errcode='42501'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-ops-account:' || v_session_username, 0));
  select actor.role,actor.username,session_row.display_name,session_row.label into v_role,v_user,v_label,v_session_label from public.rehearsal_ops_sessions session_row join public.rehearsal_ops_accounts actor on actor.username=session_row.username where session_row.id=p_session_id and session_row.username=v_session_username and session_row.revoked_at is null and session_row.expires_at>now() and actor.active and actor.credential_version=session_row.credential_version for update of session_row,actor;
  if v_role is null then raise exception 'unauthorized' using errcode='42501'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-request:' || p_request_id::text, 0));
  select * into old_receipt from public.rehearsal_ops_request_receipts where request_id=p_request_id;
  if found then
    if old_receipt.session_id<>p_session_id or old_receipt.resource_id<>p_resource_id or old_receipt.state<>p_state or old_receipt.expected_version<>p_expected_version then return jsonb_build_object('status','payload_mismatch'); end if;
    return old_receipt.result;
  end if;
  select * into resource_row from public.rehearsal_ops_resources where id=p_resource_id for update;
  if not found or (v_role <> 'superadmin' and resource_row.category <> v_role) then raise exception 'unauthorized' using errcode='42501'; end if;
  if (resource_row.id='space.songrim.access' and p_state not in ('checking','closed','school_open','gym_open','hall_open','hall_closed')) or (resource_row.id<>'space.songrim.access' and p_state not in ('checking','closed','available','busy','full')) then raise exception 'invalid state'; end if;
  if resource_row.version<>p_expected_version then result:=jsonb_build_object('status','conflict','resource',jsonb_build_object('id',resource_row.id,'label',resource_row.label,'category',resource_row.category,'state',resource_row.state,'version',resource_row.version,'updatedAt',resource_row.updated_at));
  else
    v_before:=resource_row.state;
    update public.rehearsal_ops_resources set state=p_state,version=version+1,updated_at=now() where id=resource_row.id returning * into resource_row;
    insert into public.rehearsal_ops_history(resource_id,before_state,after_state,actor_username,actor_label,session_label) values(resource_row.id,v_before,p_state,v_user,v_label,v_session_label);
    result:=jsonb_build_object('status','ok','resource',jsonb_build_object('id',resource_row.id,'label',resource_row.label,'category',resource_row.category,'state',resource_row.state,'version',resource_row.version,'updatedAt',resource_row.updated_at));
  end if;
  insert into public.rehearsal_ops_request_receipts(request_id,session_id,resource_id,state,expected_version,result) values(p_request_id,p_session_id,p_resource_id,p_state,p_expected_version,result);
  return result;
end; $$;

create or replace function public.rehearsal_ops_upsert_account(p_session_id uuid, p_username text, p_role text, p_display_label text, p_password_hash text, p_active boolean)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_actor_username text; v_role text; target_row public.rehearsal_ops_accounts%rowtype; v_revoke boolean; v_first_key text; v_second_key text;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
  if p_username is null or p_username !~ '^[A-Z0-9_-]{1,80}$' or p_role not in ('parking','space') or char_length(p_display_label) not between 1 and 30 or (p_password_hash is not null and p_password_hash !~ '^scrypt\$[0-9a-f]{32}\$[0-9a-f]{64}$') then raise exception 'invalid account'; end if;
  -- Find actor without locks, then take actor/target locks in lexical order before any account or session row lock.
  select username into v_actor_username from public.rehearsal_ops_sessions where id=p_session_id;
  if v_actor_username is null then raise exception 'unauthorized' using errcode='42501'; end if;
  v_first_key := least('rehearsal-ops-account:' || v_actor_username, 'rehearsal-ops-account:' || p_username);
  v_second_key := greatest('rehearsal-ops-account:' || v_actor_username, 'rehearsal-ops-account:' || p_username);
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_first_key, 0));
  if v_second_key <> v_first_key then perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended(v_second_key, 0)); end if;
  select actor.role into v_role from public.rehearsal_ops_sessions session_row join public.rehearsal_ops_accounts actor on actor.username=session_row.username where session_row.id=p_session_id and session_row.username=v_actor_username and session_row.revoked_at is null and session_row.expires_at>now() and actor.active and actor.credential_version=session_row.credential_version for update of session_row,actor;
  if v_role is distinct from 'superadmin' then raise exception 'unauthorized' using errcode='42501'; end if;
  select * into target_row from public.rehearsal_ops_accounts where username=p_username for update;
  if not found then
    if p_active and p_password_hash is null then raise exception 'active account requires password'; end if;
    insert into public.rehearsal_ops_accounts(username,role,display_label,password_hash,active) values(p_username,p_role,p_display_label,p_password_hash,p_active) returning * into target_row;
  else
    if target_row.role='superadmin' then raise exception 'superadmin account is immutable here' using errcode='42501'; end if;
    if p_active and coalesce(p_password_hash,target_row.password_hash) is null then raise exception 'active account requires password'; end if;
    v_revoke := p_password_hash is not null or target_row.active<>p_active or target_row.role<>p_role;
    update public.rehearsal_ops_accounts set role=p_role,display_label=p_display_label,password_hash=coalesce(p_password_hash,password_hash),active=p_active,credential_version=case when v_revoke then credential_version+1 else credential_version end,failed_attempts=case when p_password_hash is not null or (not target_row.active and p_active) then 0 else failed_attempts end,failed_window_started_at=case when p_password_hash is not null or (not target_row.active and p_active) then null else failed_window_started_at end,updated_at=now() where username=p_username returning * into target_row;
    if v_revoke then update public.rehearsal_ops_sessions set revoked_at=now() where username=p_username and revoked_at is null; end if;
  end if;
  return jsonb_build_object('username',target_row.username,'role',target_row.role,'displayLabel',target_row.display_label,'active',target_row.active,'hasPassword',target_row.password_hash is not null);
end; $$;

revoke all on function public.rehearsal_ops_reserve_login(text), public.rehearsal_ops_get_session(uuid), public.rehearsal_ops_revoke_session(uuid), public.rehearsal_ops_set_resource_state(uuid,text,text,integer,uuid), public.rehearsal_ops_upsert_account(uuid,text,text,text,text,boolean) from public, anon, authenticated;
revoke all on function public.rehearsal_ops_finish_login(text,uuid,boolean,text,text,timestamptz,integer) from public, anon, authenticated;
grant execute on function public.rehearsal_ops_reserve_login(text), public.rehearsal_ops_get_session(uuid), public.rehearsal_ops_revoke_session(uuid), public.rehearsal_ops_set_resource_state(uuid,text,text,integer,uuid), public.rehearsal_ops_upsert_account(uuid,text,text,text,text,boolean), public.rehearsal_ops_finish_login(text,uuid,boolean,text,text,timestamptz,integer) to service_role;


-- Replay 004_occupancy_and_event_history.sql

-- Percentages are nullable manual operator estimates, never measured capacity.
alter table public.rehearsal_ops_resources add column occupancy_percent integer check (occupancy_percent between 0 and 100), add column last_closed_at timestamptz, add column last_full_at timestamptz;
alter table public.rehearsal_ops_resources add constraint rehearsal_ops_access_no_occupancy check (id <> 'space.songrim.access' or occupancy_percent is null);
alter table public.rehearsal_ops_history add column before_occupancy_percent integer check (before_occupancy_percent between 0 and 100), add column after_occupancy_percent integer check (after_occupancy_percent between 0 and 100);
alter table public.rehearsal_ops_request_receipts add column occupancy_percent integer check (occupancy_percent between 0 and 100);
-- Backfill only actual transitions already recorded, not the latest recheck time.
update public.rehearsal_ops_resources r set last_closed_at=(select max(h.created_at) from public.rehearsal_ops_history h where h.resource_id=r.id and h.after_state in ('closed','hall_closed') and h.before_state<>h.after_state), last_full_at=(select max(h.created_at) from public.rehearsal_ops_history h where h.resource_id=r.id and h.after_state='full' and h.before_state<>h.after_state);
insert into public.rehearsal_ops_resources(id,label,category,state) values ('parking.calvary','갈보리교회 주차','parking','checking') on conflict(id) do nothing;
-- Remove the old overload so no write path bypasses estimate-aware receipts.
drop function public.rehearsal_ops_set_resource_state(uuid,text,text,integer,uuid);
create or replace function public.rehearsal_ops_set_resource_state(p_session_id uuid, p_resource_id text, p_state text, p_expected_version integer, p_request_id uuid, p_occupancy_percent integer default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_session_username text; v_role text; v_user text; v_label text; v_session_label text; resource_row public.rehearsal_ops_resources%rowtype; old_receipt public.rehearsal_ops_request_receipts%rowtype; result jsonb; v_before text; v_before_percent integer;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
  if p_occupancy_percent is not null and (p_occupancy_percent < 0 or p_occupancy_percent > 100 or p_resource_id='space.songrim.access') then raise exception 'invalid operator estimate'; end if;
  -- Read username without a row lock, acquire its advisory lock, then reauthorize under row locks.
  select username into v_session_username from public.rehearsal_ops_sessions where id=p_session_id;
  if v_session_username is null then raise exception 'unauthorized' using errcode='42501'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-ops-account:' || v_session_username, 0));
  select actor.role,actor.username,session_row.display_name,session_row.label into v_role,v_user,v_label,v_session_label from public.rehearsal_ops_sessions session_row join public.rehearsal_ops_accounts actor on actor.username=session_row.username where session_row.id=p_session_id and session_row.username=v_session_username and session_row.revoked_at is null and session_row.expires_at>now() and actor.active and actor.credential_version=session_row.credential_version for update of session_row,actor;
  if v_role is null then raise exception 'unauthorized' using errcode='42501'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-request:' || p_request_id::text, 0));
  select * into old_receipt from public.rehearsal_ops_request_receipts where request_id=p_request_id;
  if found then
    if old_receipt.session_id<>p_session_id or old_receipt.resource_id<>p_resource_id or old_receipt.state<>p_state or old_receipt.expected_version<>p_expected_version or old_receipt.occupancy_percent is distinct from p_occupancy_percent then return jsonb_build_object('status','payload_mismatch'); end if;
    return old_receipt.result;
  end if;
  select * into resource_row from public.rehearsal_ops_resources where id=p_resource_id for update;
  if not found or (v_role <> 'superadmin' and resource_row.category <> v_role) then raise exception 'unauthorized' using errcode='42501'; end if;
  if (resource_row.id='space.songrim.access' and p_state not in ('checking','closed','school_open','gym_open','hall_open','hall_closed')) or (resource_row.id<>'space.songrim.access' and p_state not in ('checking','closed','available','busy','full')) then raise exception 'invalid state'; end if;
  if resource_row.version<>p_expected_version then result:=jsonb_build_object('status','conflict','resource',jsonb_build_object('id',resource_row.id,'label',resource_row.label,'category',resource_row.category,'state',resource_row.state,'version',resource_row.version,'updatedAt',resource_row.updated_at,'occupancyPercent',resource_row.occupancy_percent,'lastClosedAt',resource_row.last_closed_at,'lastFullAt',resource_row.last_full_at));
  else
    v_before:=resource_row.state; v_before_percent:=resource_row.occupancy_percent;
    update public.rehearsal_ops_resources set state=p_state,occupancy_percent=p_occupancy_percent,version=version+1,updated_at=now(),
      last_closed_at=case when p_state in ('closed','hall_closed') and state is distinct from p_state then now() else last_closed_at end,
      last_full_at=case when p_state='full' and state is distinct from p_state then now() else last_full_at end where id=resource_row.id returning * into resource_row;
    insert into public.rehearsal_ops_history(resource_id,before_state,after_state,actor_username,actor_label,session_label,before_occupancy_percent,after_occupancy_percent) values(resource_row.id,v_before,p_state,v_user,v_label,v_session_label,v_before_percent,p_occupancy_percent);
    result:=jsonb_build_object('status','ok','resource',jsonb_build_object('id',resource_row.id,'label',resource_row.label,'category',resource_row.category,'state',resource_row.state,'version',resource_row.version,'updatedAt',resource_row.updated_at,'occupancyPercent',resource_row.occupancy_percent,'lastClosedAt',resource_row.last_closed_at,'lastFullAt',resource_row.last_full_at));
  end if;
  insert into public.rehearsal_ops_request_receipts(request_id,session_id,resource_id,state,expected_version,result,occupancy_percent) values(p_request_id,p_session_id,p_resource_id,p_state,p_expected_version,result,p_occupancy_percent);
  return result;
end; $$;

create or replace function public.rehearsal_ops_list_operations(p_session_id uuid)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_role text;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
 select a.role into v_role from public.rehearsal_ops_sessions s join public.rehearsal_ops_accounts a on a.username=s.username where s.id=p_session_id and s.revoked_at is null and s.expires_at>now() and a.active and a.credential_version=s.credential_version;
 if v_role is null then raise exception 'unauthorized' using errcode='42501'; end if;
 return jsonb_build_object('resources', (select coalesce(jsonb_agg(jsonb_build_object('id',r.id,'label',r.label,'category',r.category,'state',r.state,'version',r.version,'updatedAt',r.updated_at,'occupancyPercent',r.occupancy_percent,'lastClosedAt',r.last_closed_at,'lastFullAt',r.last_full_at) order by r.id),'[]'::jsonb) from public.rehearsal_ops_resources r where v_role='superadmin' or r.category=v_role), 'history', (select coalesce(jsonb_agg(jsonb_build_object('id',recent.id,'resourceId',recent.resource_id,'beforeState',recent.before_state,'afterState',recent.after_state,'beforeOccupancyPercent',recent.before_occupancy_percent,'afterOccupancyPercent',recent.after_occupancy_percent,'actorUsername',recent.actor_username,'actorLabel',recent.actor_label,'sessionLabel',recent.session_label,'createdAt',recent.created_at) order by recent.created_at desc),'[]'::jsonb) from (select h.* from public.rehearsal_ops_history h join public.rehearsal_ops_resources r on r.id=h.resource_id where v_role='superadmin' or r.category=v_role order by h.created_at desc limit 100) recent), 'canManageAccounts',v_role='superadmin');
end; $$;
create or replace function public.rehearsal_ops_public_resources()
returns jsonb language sql stable security definer set search_path = '' as $$
 select coalesce(jsonb_agg(jsonb_build_object('id',id,'label',label,'category',category,'state',state,'version',version,'updatedAt',updated_at,'occupancyPercent',occupancy_percent,'lastClosedAt',last_closed_at,'lastFullAt',last_full_at) order by id),'[]'::jsonb) from public.rehearsal_ops_resources;
$$;


revoke all on function public.rehearsal_ops_set_resource_state(uuid,text,text,integer,uuid,integer), public.rehearsal_ops_list_operations(uuid), public.rehearsal_ops_public_resources() from public, anon, authenticated;
grant execute on function public.rehearsal_ops_set_resource_state(uuid,text,text,integer,uuid,integer), public.rehearsal_ops_list_operations(uuid), public.rehearsal_ops_public_resources() to service_role;


-- Replay 005_community.sql
-- Requires operations sessions (002/003), NOT migration 004. No public storage policies.
-- Suggested post-event retention review 2026-11-10; no automatic full purge.
-- If the operator chooses full removal, delete ALL bucket objects via Storage API first,
-- then TRUNCATE public.rehearsal_community_v2_items, public.rehearsal_community_v2_rates,
-- public.rehearsal_community_v2_audit; do not delete storage.objects directly.
-- Hourly /api/community/cleanup repairs orphan storage only, not approved posts.
-- Operator must approve and verify any full content/receipt/audit removal.

create table if not exists public.rehearsal_community_v2_items (
 id uuid primary key, kind text not null check(kind in ('prayer','photo')),
 text text not null, event_day integer check(event_day between 0 and 5),
 status text not null default 'pending' check(status in ('pending','approved','rejected','deleted')),
 version integer not null default 0, created_at timestamptz not null default now(),
 token_hash text not null check(token_hash ~ '^[0-9a-f]{64}$'),
 payload_hash text not null check(payload_hash ~ '^[0-9a-f]{64}$'),
 path text, ready boolean not null default false,
 check(length(text)<=case when kind='prayer' then 600 else 40 end)
);
alter table public.rehearsal_community_v2_items add column if not exists last_cleanup_at timestamptz;
create table if not exists public.rehearsal_community_v2_rates (key text primary key, window_start timestamptz not null, hits integer not null);
create table if not exists public.rehearsal_community_v2_audit (id bigint generated always as identity primary key, item_id uuid not null, decision text not null, actor text, created_at timestamptz not null default now());
create index if not exists rehearsal_community_v2_recent on public.rehearsal_community_v2_items(status,created_at desc);
alter table public.rehearsal_community_v2_items enable row level security;
alter table public.rehearsal_community_v2_rates enable row level security;
alter table public.rehearsal_community_v2_audit enable row level security;
revoke all on public.rehearsal_community_v2_items, public.rehearsal_community_v2_rates, public.rehearsal_community_v2_audit from public,anon,authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
values('rehearsal-community-photos-v2','rehearsal-community-photos-v2',false,3145728,array['image/png'])
on conflict(id) do update set public=false,file_size_limit=3145728,allowed_mime_types=array['image/png'];
create or replace function public.rehearsal_community_v2(p_action text,p_args jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare
 r public.rehearsal_community_v2_items%rowtype; v_today date := (now() at time zone 'Asia/Seoul')::date;
 v_count bigint; v_session jsonb; v_actor text; v_result jsonb; v_key text; v_hits integer;
 v_window timestamptz := date_trunc('minute',now()); v_id uuid; v_cleanup text;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
 -- Moderator authentication is revalidated within the same transaction, serialized
 -- with account revocation/password changes; row locks cover direct revocations.
 if p_action in ('adminList','moderate') or (p_action='photo' and p_args->>'session' is not null) then
  select username into v_actor from public.rehearsal_ops_sessions where id=(p_args->>'session')::uuid;
  if v_actor is null then raise exception 'unauthorized' using errcode='42501'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-ops-account:'||v_actor,0));
  perform 1 from public.rehearsal_ops_sessions s join public.rehearsal_ops_accounts a on a.username=s.username where s.id=(p_args->>'session')::uuid for update of s,a;
  select public.rehearsal_ops_get_session((p_args->>'session')::uuid) into v_session;
  if v_session is null or v_session->>'role'<>'superadmin' then raise exception 'unauthorized' using errcode='42501'; end if;
 end if;
 if p_action='preflight' then
  if coalesce(p_args->>'ipHash','') !~ '^[0-9a-f]{64}$' then raise exception 'invalid ip hash'; end if;
  insert into public.rehearsal_community_v2_rates(key,window_start,hits) values('attempt:'||(p_args->>'ipHash'),v_window,1)
  on conflict(key) do update set window_start=excluded.window_start,hits=case when rehearsal_community_v2_rates.window_start=excluded.window_start then rehearsal_community_v2_rates.hits+1 else 1 end returning hits into v_hits;
  return jsonb_build_object('status',case when v_hits>240 then 'limited' else 'ok' end);
 elsif p_action='cleanupCandidates' then
  v_result:='[]'::jsonb;
  -- Row locks serialize stale expiry with finish. Paths remain tombstones forever
  -- until retention cleanup, so late uploads are removed on a future sweep.
  for r in select * from public.rehearsal_community_v2_items
   where kind='photo' and path is not null and
    (status in ('rejected','deleted') or (status='pending' and not ready and created_at<now()-interval '1 hour'))
   order by last_cleanup_at asc nulls first,created_at,id limit 50 for update skip locked
  loop
   if r.status='pending' then
    update public.rehearsal_community_v2_items set status='deleted',text='',event_day=null,ready=false,version=version+1 where id=r.id;
    insert into public.rehearsal_community_v2_audit(item_id,decision,actor) values(r.id,'deleted','orphan-cleanup');
   end if;
   v_result:=v_result||jsonb_build_array(jsonb_build_object('id',r.id,'path',r.path));
  end loop;
  return jsonb_build_object('items',v_result);
 elsif p_action='cleanupComplete' then
  update public.rehearsal_community_v2_items set last_cleanup_at=now()
   where id=(p_args->>'id')::uuid and path=p_args->>'path' and status in ('rejected','deleted');
  if not found then return jsonb_build_object('status','conflict'); end if;
  return jsonb_build_object('status','ok');
 end if;
 if p_action in ('submit','finish','delete','status','moderate','photo') then
  v_id:=(p_args->>'id')::uuid;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-community:'||v_id::text,0));
  select * into r from public.rehearsal_community_v2_items where id=v_id for update;
 end if;
 if p_action='submit' then
  if r.id is not null then
   if r.token_hash<>p_args->>'tokenHash' or r.payload_hash<>p_args->>'payloadHash' then return jsonb_build_object('status','payload_mismatch'); end if;
  else
   if p_args->>'kind' not in ('photo','prayer') or p_args->>'ipHash' !~ '^[0-9a-f]{64}$' or p_args->>'tokenHash' !~ '^[0-9a-f]{64}$' or p_args->>'payloadHash' !~ '^[0-9a-f]{64}$' then raise exception 'invalid submission'; end if;
   -- Consistent lock ordering: IP bucket then token bucket. Atomic counters count
   -- fresh IDs, not retries; shared NAT gets 60 photos or 120 prayers/minute.
   foreach v_key in array array['ip:'||(p_args->>'kind')||':'||(p_args->>'ipHash'),'token:'||(p_args->>'tokenHash')] loop
    insert into public.rehearsal_community_v2_rates(key,window_start,hits) values(v_key,v_window,1)
    on conflict(key) do update set window_start=excluded.window_start,hits=case when rehearsal_community_v2_rates.window_start=excluded.window_start then rehearsal_community_v2_rates.hits+1 else 1 end returning hits into v_hits;
    if v_hits > (case when v_key like 'token:%' then 10 when p_args->>'kind'='photo' then 60 else 120 end) then return jsonb_build_object('status','limited'); end if;
   end loop;
   insert into public.rehearsal_community_v2_items(id,kind,text,event_day,token_hash,payload_hash,path,ready)
   values(v_id,p_args->>'kind',p_args->>'text',(p_args->>'eventDay')::integer,p_args->>'tokenHash',p_args->>'payloadHash',case when p_args->>'kind'='photo' then v_id::text||'.png' end,p_args->>'kind'='prayer') returning * into r;
  end if;
 elsif p_action in ('finish','status','delete') then
  if r.id is null or r.token_hash<>p_args->>'tokenHash' then return jsonb_build_object('status','missing'); end if;
  if p_action='finish' then
   if r.payload_hash<>p_args->>'payloadHash' then return jsonb_build_object('status','payload_mismatch'); end if;
   if r.status='pending' and not r.ready then update public.rehearsal_community_v2_items set ready=true,created_at=now() where id=v_id returning * into r; elsif r.status in ('rejected','deleted') then v_cleanup:=r.path; end if;
  elsif p_action='delete' then
   v_cleanup:=r.path;
   if r.status<>'deleted' then
    update public.rehearsal_community_v2_items set status='deleted',text='',event_day=null,ready=false,version=version+1 where id=v_id returning * into r;
    insert into public.rehearsal_community_v2_audit(item_id,decision) values(v_id,'deleted');
   end if;
  end if;
 elsif p_action='moderate' then
  if r.id is null then return jsonb_build_object('status','missing'); end if;
  if p_args->>'decision' not in ('approved','rejected','deleted') then raise exception 'invalid decision'; end if;
  -- Repeating a destructive decision can retry failed object cleanup safely.
  if r.status in ('rejected','deleted') and r.status=p_args->>'decision' then v_cleanup:=r.path;
  else
   if r.version<>(p_args->>'expectedVersion')::integer then return jsonb_build_object('status','conflict'); end if;
   if r.status='deleted' or (r.status='rejected' and p_args->>'decision'<>'deleted') or (p_args->>'decision'='approved' and not r.ready) then return jsonb_build_object('status','conflict'); end if;
   update public.rehearsal_community_v2_items set status=p_args->>'decision',version=version+1,
    text=case when p_args->>'decision'='approved' then text else '' end,
    event_day=case when p_args->>'decision'='approved' then event_day else null end,
    ready=case when p_args->>'decision'='approved' then ready else false end
    where id=v_id returning * into r;
   insert into public.rehearsal_community_v2_audit(item_id,decision,actor) values(v_id,r.status,v_actor);
   if r.status in ('rejected','deleted') then v_cleanup:=r.path; end if;
  end if;
 elsif p_action='photo' then
  if r.id is null or r.kind<>'photo' or not r.ready or not (r.status='approved' or (r.status='pending' and coalesce(v_session->>'role'='superadmin',false))) then return jsonb_build_object('status','missing'); end if;
  return jsonb_build_object('path',r.path);
 elsif p_action not in ('list','adminList') then raise exception 'invalid action';
 end if;
 if r.status in ('rejected','deleted') then v_cleanup:=r.path; end if;
 select count(*) into v_count from public.rehearsal_community_v2_items where kind='photo' and ready and status in ('pending','approved') and created_at>=v_today::timestamp at time zone 'Asia/Seoul' and created_at<(v_today+1)::timestamp at time zone 'Asia/Seoul';
 if p_action in ('list','adminList') then
  select coalesce(jsonb_agg(x.item order by x.created_at desc),'[]'::jsonb) into v_result from (
   select c.created_at,jsonb_build_object('id',c.id,'kind',c.kind,'text',c.text,'createdAt',c.created_at,'eventDay',c.event_day)
   ||case when c.kind='photo' and c.ready and c.status in ('pending','approved') then jsonb_build_object('photoUrl','/api/community/photo?id='||c.id::text) else '{}'::jsonb end
   ||case when p_action='adminList' then jsonb_build_object('status',c.status,'version',c.version) else '{}'::jsonb end as item
   from public.rehearsal_community_v2_items c where (p_action='adminList' or (c.kind=p_args->>'kind' and c.status='approved' and c.ready))
   order by case when p_action='adminList' and c.status='pending' then 0 else 1 end,c.created_at desc limit case when p_action='adminList' then 100 else 30 end
  ) x;
  return jsonb_build_object('enabled',true,'items',v_result,'photoCountToday',v_count,'today',v_today);
 end if;
 return jsonb_build_object('id',r.id,'status',r.status,'photoCountToday',v_count,'today',v_today)
 ||case when p_action='submit' then jsonb_build_object('ready',r.ready,'path',r.path) else '{}'::jsonb end
 ||case when p_action in ('status','moderate') then jsonb_build_object('version',r.version) else '{}'::jsonb end
 ||case when v_cleanup is not null then jsonb_build_object('cleanupPath',v_cleanup) else '{}'::jsonb end;
end; $$;
revoke all on function public.rehearsal_community_v2(text,jsonb) from public,anon,authenticated;
grant execute on function public.rehearsal_community_v2(text,jsonb) to service_role;


-- Replay 006_reflections.sql
-- Add text-only reflections without modifying the deployed 005 migration.

-- Constraint names may be autogenerated or manually named. Remove only the old
-- kind and text-length checks by their definitions, then install explicit names.
do $constraints$
declare v_constraint text;
begin
 for v_constraint in
  select conname
  from pg_catalog.pg_constraint
  where conrelid='public.rehearsal_community_v2_items'::pg_catalog.regclass
    and contype='c'
    and (
      pg_catalog.pg_get_constraintdef(oid) ~ $rx$\mkind\M.*\mprayer\M.*\mphoto\M$rx$
      or pg_catalog.pg_get_constraintdef(oid) ~ $rx$\mlength\M.*\mtext\M$rx$
    )
 loop
  execute pg_catalog.format('alter table public.rehearsal_community_v2_items drop constraint %I',v_constraint);
 end loop;
end $constraints$;
alter table public.rehearsal_community_v2_items
 add constraint rehearsal_community_v2_items_kind_check check(kind in ('prayer','photo','reflection')),
 add constraint rehearsal_community_v2_items_text_length_check check(length(text)<=case when kind='prayer' then 600 when kind='reflection' then 1000 else 40 end);

create or replace function public.rehearsal_community_v2(p_action text,p_args jsonb)
returns jsonb language plpgsql security definer set search_path='' as $$
declare
 r public.rehearsal_community_v2_items%rowtype; v_today date := (now() at time zone 'Asia/Seoul')::date;
 v_count bigint; v_session jsonb; v_actor text; v_result jsonb; v_key text; v_hits integer;
 v_window timestamptz := date_trunc('minute',now()); v_id uuid; v_cleanup text;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
 -- Moderator authentication is revalidated within the same transaction, serialized
 -- with account revocation/password changes; row locks cover direct revocations.
 if p_action in ('adminList','moderate') or (p_action='photo' and p_args->>'session' is not null) then
  select username into v_actor from public.rehearsal_ops_sessions where id=(p_args->>'session')::uuid;
  if v_actor is null then raise exception 'unauthorized' using errcode='42501'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-ops-account:'||v_actor,0));
  perform 1 from public.rehearsal_ops_sessions s join public.rehearsal_ops_accounts a on a.username=s.username where s.id=(p_args->>'session')::uuid for update of s,a;
  select public.rehearsal_ops_get_session((p_args->>'session')::uuid) into v_session;
  if v_session is null or v_session->>'role'<>'superadmin' then raise exception 'unauthorized' using errcode='42501'; end if;
 end if;
 if p_action='preflight' then
  if coalesce(p_args->>'ipHash','') !~ '^[0-9a-f]{64}$' then raise exception 'invalid ip hash'; end if;
  insert into public.rehearsal_community_v2_rates(key,window_start,hits) values('attempt:'||(p_args->>'ipHash'),v_window,1)
  on conflict(key) do update set window_start=excluded.window_start,hits=case when rehearsal_community_v2_rates.window_start=excluded.window_start then rehearsal_community_v2_rates.hits+1 else 1 end returning hits into v_hits;
  return jsonb_build_object('status',case when v_hits>240 then 'limited' else 'ok' end);
 elsif p_action='cleanupCandidates' then
  v_result:='[]'::jsonb;
  -- Row locks serialize stale expiry with finish. Paths remain tombstones forever
  -- until retention cleanup, so late uploads are removed on a future sweep.
  for r in select * from public.rehearsal_community_v2_items
   where kind='photo' and path is not null and
    (status in ('rejected','deleted') or (status='pending' and not ready and created_at<now()-interval '1 hour'))
   order by last_cleanup_at asc nulls first,created_at,id limit 50 for update skip locked
  loop
   if r.status='pending' then
    update public.rehearsal_community_v2_items set status='deleted',text='',event_day=null,ready=false,version=version+1 where id=r.id;
    insert into public.rehearsal_community_v2_audit(item_id,decision,actor) values(r.id,'deleted','orphan-cleanup');
   end if;
   v_result:=v_result||jsonb_build_array(jsonb_build_object('id',r.id,'path',r.path));
  end loop;
  return jsonb_build_object('items',v_result);
 elsif p_action='cleanupComplete' then
  update public.rehearsal_community_v2_items set last_cleanup_at=now()
   where id=(p_args->>'id')::uuid and path=p_args->>'path' and status in ('rejected','deleted');
  if not found then return jsonb_build_object('status','conflict'); end if;
  return jsonb_build_object('status','ok');
 end if;
 if p_action in ('submit','finish','delete','status','moderate','photo') then
  v_id:=(p_args->>'id')::uuid;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-community:'||v_id::text,0));
  select * into r from public.rehearsal_community_v2_items where id=v_id for update;
 end if;
 if p_action='submit' then
  if r.id is not null then
   if r.token_hash<>p_args->>'tokenHash' or r.payload_hash<>p_args->>'payloadHash' then return jsonb_build_object('status','payload_mismatch'); end if;
  else
   if p_args->>'kind' not in ('photo','prayer','reflection') or p_args->>'ipHash' !~ '^[0-9a-f]{64}$' or p_args->>'tokenHash' !~ '^[0-9a-f]{64}$' or p_args->>'payloadHash' !~ '^[0-9a-f]{64}$' then raise exception 'invalid submission'; end if;
   -- Consistent lock ordering: IP bucket then token bucket. Atomic counters count
   -- fresh IDs, not retries; shared NAT gets 60 photos or 120 prayers/minute.
   foreach v_key in array array['ip:'||(p_args->>'kind')||':'||(p_args->>'ipHash'),'token:'||(p_args->>'tokenHash')] loop
    insert into public.rehearsal_community_v2_rates(key,window_start,hits) values(v_key,v_window,1)
    on conflict(key) do update set window_start=excluded.window_start,hits=case when rehearsal_community_v2_rates.window_start=excluded.window_start then rehearsal_community_v2_rates.hits+1 else 1 end returning hits into v_hits;
    if v_hits > (case when v_key like 'token:%' then 10 when p_args->>'kind'='photo' then 60 else 120 end) then return jsonb_build_object('status','limited'); end if;
   end loop;
   insert into public.rehearsal_community_v2_items(id,kind,text,event_day,token_hash,payload_hash,path,ready)
   values(v_id,p_args->>'kind',p_args->>'text',(p_args->>'eventDay')::integer,p_args->>'tokenHash',p_args->>'payloadHash',case when p_args->>'kind'='photo' then v_id::text||'.png' end,p_args->>'kind' in ('prayer','reflection')) returning * into r;
  end if;
 elsif p_action in ('finish','status','delete') then
  if r.id is null or r.token_hash<>p_args->>'tokenHash' then return jsonb_build_object('status','missing'); end if;
  if p_action='finish' then
   if r.payload_hash<>p_args->>'payloadHash' then return jsonb_build_object('status','payload_mismatch'); end if;
   if r.status='pending' and not r.ready then update public.rehearsal_community_v2_items set ready=true,created_at=now() where id=v_id returning * into r; elsif r.status in ('rejected','deleted') then v_cleanup:=r.path; end if;
  elsif p_action='delete' then
   v_cleanup:=r.path;
   if r.status<>'deleted' then
    update public.rehearsal_community_v2_items set status='deleted',text='',event_day=null,ready=false,version=version+1 where id=v_id returning * into r;
    insert into public.rehearsal_community_v2_audit(item_id,decision) values(v_id,'deleted');
   end if;
  end if;
 elsif p_action='moderate' then
  if r.id is null then return jsonb_build_object('status','missing'); end if;
  if p_args->>'decision' not in ('approved','rejected','deleted') then raise exception 'invalid decision'; end if;
  -- Repeating a destructive decision can retry failed object cleanup safely.
  if r.status in ('rejected','deleted') and r.status=p_args->>'decision' then v_cleanup:=r.path;
  else
   if r.version<>(p_args->>'expectedVersion')::integer then return jsonb_build_object('status','conflict'); end if;
   if r.status='deleted' or (r.status='rejected' and p_args->>'decision'<>'deleted') or (p_args->>'decision'='approved' and not r.ready) then return jsonb_build_object('status','conflict'); end if;
   update public.rehearsal_community_v2_items set status=p_args->>'decision',version=version+1,
    text=case when p_args->>'decision'='approved' then text else '' end,
    event_day=case when p_args->>'decision'='approved' then event_day else null end,
    ready=case when p_args->>'decision'='approved' then ready else false end
    where id=v_id returning * into r;
   insert into public.rehearsal_community_v2_audit(item_id,decision,actor) values(v_id,r.status,v_actor);
   if r.status in ('rejected','deleted') then v_cleanup:=r.path; end if;
  end if;
 elsif p_action='photo' then
  if r.id is null or r.kind<>'photo' or not r.ready or not (r.status='approved' or (r.status='pending' and coalesce(v_session->>'role'='superadmin',false))) then return jsonb_build_object('status','missing'); end if;
  return jsonb_build_object('path',r.path);
 elsif p_action not in ('list','adminList') then raise exception 'invalid action';
 end if;
 if r.status in ('rejected','deleted') then v_cleanup:=r.path; end if;
 select count(*) into v_count from public.rehearsal_community_v2_items where kind='photo' and ready and status in ('pending','approved') and created_at>=v_today::timestamp at time zone 'Asia/Seoul' and created_at<(v_today+1)::timestamp at time zone 'Asia/Seoul';
 if p_action in ('list','adminList') then
  select coalesce(jsonb_agg(x.item order by x.created_at desc),'[]'::jsonb) into v_result from (
   select c.created_at,jsonb_build_object('id',c.id,'kind',c.kind,'text',c.text,'createdAt',c.created_at,'eventDay',c.event_day)
   ||case when c.kind='photo' and c.ready and c.status in ('pending','approved') then jsonb_build_object('photoUrl','/api/community/photo?id='||c.id::text) else '{}'::jsonb end
   ||case when p_action='adminList' then jsonb_build_object('status',c.status,'version',c.version) else '{}'::jsonb end as item
   from public.rehearsal_community_v2_items c where (p_action='adminList' or (c.kind=p_args->>'kind' and c.status='approved' and c.ready))
   order by case when p_action='adminList' and c.status='pending' then 0 else 1 end,c.created_at desc limit case when p_action='adminList' then 100 else 30 end
  ) x;
  return jsonb_build_object('enabled',true,'items',v_result,'photoCountToday',v_count,'today',v_today);
 end if;
 return jsonb_build_object('id',r.id,'status',r.status,'photoCountToday',v_count,'today',v_today)
 ||case when p_action='submit' then jsonb_build_object('ready',r.ready,'path',r.path) else '{}'::jsonb end
 ||case when p_action in ('status','moderate') then jsonb_build_object('version',r.version) else '{}'::jsonb end
 ||case when v_cleanup is not null then jsonb_build_object('cleanupPath',v_cleanup) else '{}'::jsonb end;
end; $$;
revoke all on function public.rehearsal_community_v2(text,jsonb) from public,anon,authenticated;
grant execute on function public.rehearsal_community_v2(text,jsonb) to service_role;


-- Replay 007_occupancy_steps.sql

-- A displayed estimate is a discrete operator choice. These checks deliberately
-- validate existing rows too: this migration must fail rather than round or invent history.
alter table public.rehearsal_ops_resources add constraint rehearsal_ops_resources_occupancy_percent_step check (occupancy_percent is null or occupancy_percent % 10 = 0);
alter table public.rehearsal_ops_history add constraint rehearsal_ops_history_before_occupancy_percent_step check (before_occupancy_percent is null or before_occupancy_percent % 10 = 0), add constraint rehearsal_ops_history_after_occupancy_percent_step check (after_occupancy_percent is null or after_occupancy_percent % 10 = 0);
alter table public.rehearsal_ops_request_receipts add constraint rehearsal_ops_request_receipts_occupancy_percent_step check (occupancy_percent is null or occupancy_percent % 10 = 0);

-- Keep the six-argument RPC and its fifth-argument-compatible default. A null
-- estimate is intentional: older callers may still record available/busy/full
-- without fabricating a percentage.
create or replace function public.rehearsal_ops_set_resource_state(p_session_id uuid, p_resource_id text, p_state text, p_expected_version integer, p_request_id uuid, p_occupancy_percent integer default null)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare v_session_username text; v_role text; v_user text; v_label text; v_session_label text; resource_row public.rehearsal_ops_resources%rowtype; old_receipt public.rehearsal_ops_request_receipts%rowtype; result jsonb; v_before text; v_before_percent integer;
begin
  perform pg_catalog.pg_advisory_xact_lock_shared(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
  if p_occupancy_percent is not null then
    if p_occupancy_percent < 0 or p_occupancy_percent > 100 or p_occupancy_percent % 10 <> 0 or p_resource_id='space.songrim.access' then raise exception 'invalid operator estimate'; end if;
    if (p_state='available' and p_occupancy_percent between 0 and 60)
      or (p_state='busy' and p_occupancy_percent between 70 and 90)
      or (p_state='full' and p_occupancy_percent=100) then null;
    else raise exception 'operator estimate does not match state';
    end if;
  end if;
  -- Read username without a row lock, acquire its advisory lock, then reauthorize under row locks.
  select username into v_session_username from public.rehearsal_ops_sessions where id=p_session_id;
  if v_session_username is null then raise exception 'unauthorized' using errcode='42501'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-ops-account:' || v_session_username, 0));
  select actor.role,actor.username,session_row.display_name,session_row.label into v_role,v_user,v_label,v_session_label from public.rehearsal_ops_sessions session_row join public.rehearsal_ops_accounts actor on actor.username=session_row.username where session_row.id=p_session_id and session_row.username=v_session_username and session_row.revoked_at is null and session_row.expires_at>now() and actor.active and actor.credential_version=session_row.credential_version for update of session_row,actor;
  if v_role is null then raise exception 'unauthorized' using errcode='42501'; end if;
  perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-request:' || p_request_id::text, 0));
  select * into old_receipt from public.rehearsal_ops_request_receipts where request_id=p_request_id;
  if found then
    if old_receipt.session_id<>p_session_id or old_receipt.resource_id<>p_resource_id or old_receipt.state<>p_state or old_receipt.expected_version<>p_expected_version or old_receipt.occupancy_percent is distinct from p_occupancy_percent then return jsonb_build_object('status','payload_mismatch'); end if;
    return old_receipt.result;
  end if;
  select * into resource_row from public.rehearsal_ops_resources where id=p_resource_id for update;
  if not found or (v_role <> 'superadmin' and resource_row.category <> v_role) then raise exception 'unauthorized' using errcode='42501'; end if;
  if (resource_row.id='space.songrim.access' and p_state not in ('checking','closed','school_open','gym_open','hall_open','hall_closed')) or (resource_row.id<>'space.songrim.access' and p_state not in ('checking','closed','available','busy','full')) then raise exception 'invalid state'; end if;
  if resource_row.version<>p_expected_version then result:=jsonb_build_object('status','conflict','resource',jsonb_build_object('id',resource_row.id,'label',resource_row.label,'category',resource_row.category,'state',resource_row.state,'version',resource_row.version,'updatedAt',resource_row.updated_at,'occupancyPercent',resource_row.occupancy_percent,'lastClosedAt',resource_row.last_closed_at,'lastFullAt',resource_row.last_full_at));
  else
    v_before:=resource_row.state; v_before_percent:=resource_row.occupancy_percent;
    update public.rehearsal_ops_resources set state=p_state,occupancy_percent=p_occupancy_percent,version=version+1,updated_at=now(),
      last_closed_at=case when p_state in ('closed','hall_closed') and state is distinct from p_state then now() else last_closed_at end,
      last_full_at=case when p_state='full' and state is distinct from p_state then now() else last_full_at end where id=resource_row.id returning * into resource_row;
    insert into public.rehearsal_ops_history(resource_id,before_state,after_state,actor_username,actor_label,session_label,before_occupancy_percent,after_occupancy_percent) values(resource_row.id,v_before,p_state,v_user,v_label,v_session_label,v_before_percent,p_occupancy_percent);
    result:=jsonb_build_object('status','ok','resource',jsonb_build_object('id',resource_row.id,'label',resource_row.label,'category',resource_row.category,'state',resource_row.state,'version',resource_row.version,'updatedAt',resource_row.updated_at,'occupancyPercent',resource_row.occupancy_percent,'lastClosedAt',resource_row.last_closed_at,'lastFullAt',resource_row.last_full_at));
  end if;
  insert into public.rehearsal_ops_request_receipts(request_id,session_id,resource_id,state,expected_version,result,occupancy_percent) values(p_request_id,p_session_id,p_resource_id,p_state,p_expected_version,result,p_occupancy_percent);
  return result;
end; $$;

revoke all on function public.rehearsal_ops_set_resource_state(uuid,text,text,integer,uuid,integer) from public, anon, authenticated;
grant execute on function public.rehearsal_ops_set_resource_state(uuid,text,text,integer,uuid,integer) to service_role;


-- Replay 008_previous_day_parking.sql

-- Derive only observed transitions on the previous Korea calendar day.
-- A repeated full/closed check is not a new event. Initial checking -> closed
-- is not evidence that parking operated and then closed.
create or replace function public.rehearsal_ops_public_resources()
returns jsonb language sql stable security definer set search_path = '' as $$
 with bounds as (
  select (now() at time zone 'Asia/Seoul')::date as today
 ), previous as (
  select h.resource_id,
   min(h.created_at) filter(where h.after_state='full' and h.before_state<>'full') as first_full_at,
   max(h.created_at) filter(where h.after_state='closed' and h.before_state in ('available','busy','full')) as closed_at
  from public.rehearsal_ops_history h cross join bounds b
  where h.created_at >= (b.today-1)::timestamp at time zone 'Asia/Seoul'
    and h.created_at < b.today::timestamp at time zone 'Asia/Seoul'
  group by h.resource_id
 )
 select coalesce(jsonb_agg(jsonb_build_object(
  'id',r.id,'label',r.label,'category',r.category,'state',r.state,'version',r.version,
  'updatedAt',r.updated_at,'occupancyPercent',r.occupancy_percent,
  'lastClosedAt',r.last_closed_at,'lastFullAt',r.last_full_at
 ) || case when r.category='parking' then jsonb_build_object('previousDay',jsonb_build_object(
  'date',b.today-1,'firstFullAt',p.first_full_at,'closedAt',p.closed_at
 )) else '{}'::jsonb end order by r.id),'[]'::jsonb)
 from public.rehearsal_ops_resources r cross join bounds b left join previous p on p.resource_id=r.id;
$$;
revoke all on function public.rehearsal_ops_public_resources() from public,anon,authenticated;
grant execute on function public.rehearsal_ops_public_resources() to service_role;


-- Remove any bootstrap sample accounts before the ONE-TIME canonical copy.
delete from public.rehearsal_ops_accounts;
insert into public.rehearsal_ops_accounts(username,role,display_label,password_hash,active)
 select username,role,display_label,password_hash,active from public.ops_accounts;

create function public.rehearsal_ops_reset_rehearsal(p_session_id uuid)
returns jsonb language plpgsql security definer set search_path='' as $$
declare v_username text; v_role text;
begin
 -- Global exclusive lock first: no mutation may cross a reset boundary.
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-global-reset', 0));
 select username into v_username from public.rehearsal_ops_sessions where id=p_session_id;
 if v_username is null then raise exception 'unauthorized' using errcode='42501'; end if;
 perform pg_catalog.pg_advisory_xact_lock(pg_catalog.hashtextextended('rehearsal-ops-account:' || v_username, 0));
 select a.role into v_role from public.rehearsal_ops_sessions s
 join public.rehearsal_ops_accounts a on a.username=s.username
 where s.id=p_session_id and s.username=v_username and s.revoked_at is null
 and s.expires_at>now() and a.active and a.credential_version=s.credential_version
 for update of s,a;
 if v_role is distinct from 'superadmin' then raise exception 'unauthorized' using errcode='42501'; end if;
 update public.rehearsal_ops_resources set state='checking',occupancy_percent=null,
 updated_at=null,last_closed_at=null,last_full_at=null,version=version+1;
 delete from public.rehearsal_ops_history;
 delete from public.rehearsal_ops_request_receipts;
 delete from public.rehearsal_community_v2_rates;
 delete from public.rehearsal_community_v2_audit;
 -- Keep path/token/payload tombstones indefinitely for late-upload cleanup and
 -- idempotent retries. Never remove storage.objects or return private paths.
 update public.rehearsal_community_v2_items set status='deleted',text='',event_day=null,
 ready=false,version=version+1,last_cleanup_at=null;
 return jsonb_build_object('reset',true);
end; $$;
revoke all on function public.rehearsal_ops_reset_rehearsal(uuid) from public,anon,authenticated;
grant execute on function public.rehearsal_ops_reset_rehearsal(uuid) to service_role;
commit;
