// PGLITE_MODULE=/absolute/path/to/@electric-sql/pglite/dist/index.js node tests/scripts/rehearsal-db.mjs
import assert from 'node:assert/strict';
import { readFile, readdir } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
const { PGlite } = await import(process.env.PGLITE_MODULE || '@electric-sql/pglite');
const db = new PGlite();
let checks=0;
const ok=(condition,message)=>{assert.ok(condition,message);checks++;console.log(`PASS ${message}`);};
const rows=async(sql,args=[]) => (await db.query(sql,args)).rows;
const scalar=async(sql,args=[]) => Object.values((await rows(sql,args))[0])[0];
const rpc=async(name,args)=>scalar(`select public.${name}(${args.map((_,i)=>`$${i+1}`).join(',')})`,args);
async function deny(fn,label){await assert.rejects(fn); checks++; console.log(`PASS ${label}`);}
const dir=new URL('../../supabase/migrations/',import.meta.url);
const files=(await readdir(dir)).filter(f=>/^00[2-8]_/.test(f)).sort();
await db.exec(`create role anon; create role authenticated; create role service_role;
create schema storage; create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key,bucket_id text,name text);
`);
for(const file of files) await db.exec(await readFile(new URL(file,dir),'utf8'));
const hash='scrypt$'+'a'.repeat(32)+'$'+'b'.repeat(64);
await db.query(`insert into public.ops_accounts(username,role,display_label,password_hash,active,credential_version,failed_attempts) values
('ADMIN','superadmin','Live admin',$1,true,7,4),('PARK','parking','Live park',$1,true,2,3),('OFF','space','Disabled',$1,false,3,2)`,[hash]);
const liveSession=randomUUID();
await db.query(`insert into ops_sessions(id,username,credential_version,display_name,label,expires_at) values($1,'ADMIN',7,'Live person','S-0000000001',now()+interval '1 day')`,[liveSession]);
await rpc('ops_set_resource_state',[liveSession,'parking.songrim','full',0,randomUUID(),100]);
const token='a'.repeat(64),payload='b'.repeat(64),ip='c'.repeat(64);
await rpc('community_v2',['submit',{id:randomUUID(),kind:'prayer',text:'LIVE SENTINEL',tokenHash:token,payloadHash:payload,ipHash:ip}]);
await db.query(`insert into storage.objects values($1,'community-photos-v2','sentinel.png')`,[randomUUID()]);
const liveTables=(await rows(`select tablename from pg_tables where schemaname='public' order by tablename`)).map(r=>r.tablename);
async function liveSnapshot(){const result={};for(const t of liveTables)result[t]=await scalar(`select coalesce(jsonb_agg(to_jsonb(t) order by to_jsonb(t)::text),'[]'::jsonb) from public.${t} t`);result.bucket=await rows(`select * from storage.buckets where id='community-photos-v2'`);result.objects=await rows(`select * from storage.objects order by id`);result.functions=await rows(`select p.proname,pg_get_functiondef(p.oid) as definition from pg_proc p join pg_namespace n on p.pronamespace=n.oid where n.nspname='public' and (p.proname like 'ops_%' or p.proname like 'community_v2%') order by p.oid`);return result;}
const sentinel=await liveSnapshot();
const migration=await readFile(new URL('009_rehearsal.sql',dir),'utf8');
// Inject a final-statement failure: even all preceding CREATEs must roll back.
await deny(()=>db.exec(migration.replace(/commit;\s*$/, "select 1/0; commit;")), 'forced install failure aborts atomic transaction');
await db.exec('rollback');
ok(await scalar("select to_regclass('public.rehearsal_ops_accounts') is null"),'failed install leaves no rehearsal schema behind');
ok(await scalar("select count(*) from storage.buckets where id='rehearsal-community-photos-v2'")==0,'failed install leaves no rehearsal bucket behind');
assert.deepEqual(await liveSnapshot(),sentinel);
await db.exec(migration);
ok(JSON.stringify(await liveSnapshot())===JSON.stringify(sentinel),'migration leaves every live table, function, bucket and storage object unchanged');
ok(await scalar(`select count(*) from rehearsal_ops_accounts`)==3,'only canonical accounts copied, no bootstrap sample accounts');
ok(await scalar(`select bool_and(r.role=l.role and r.display_label=l.display_label and r.password_hash=l.password_hash and r.active=l.active) from rehearsal_ops_accounts r join ops_accounts l using(username)`),'account role/label/password/active copies match');
for(const t of ['sessions','login_reservations','history','request_receipts'])ok(await scalar(`select count(*) from rehearsal_ops_${t}`)==0,`no live ${t} copied`);
ok(await scalar(`select bool_and(credential_version=1 and failed_attempts=0) from rehearsal_ops_accounts`),'credential versions and failed attempts start fresh');
ok(await scalar(`select public=false from storage.buckets where id='rehearsal-community-photos-v2'`),'rehearsal photo bucket private');
let label=2;
async function login(user){const reserved=await rpc('rehearsal_ops_reserve_login',[user]);return (await rpc('rehearsal_ops_finish_login',[user,reserved.reservationId,true,'Rehearsal','S-'+String(label++).padStart(10,'0'),new Date(Date.now()+86400000).toISOString(),reserved.credentialVersion])).id;}
const admin=await login('ADMIN'), park=await login('PARK');
ok(Boolean(admin&&park),'copied active accounts can complete reservation-bound login');
ok((await rpc('rehearsal_ops_reserve_login',['OFF'])).status==='invalid','disabled copy cannot log in');
await rpc('rehearsal_ops_upsert_account',[admin,'PARK','parking','Rehearsal label',null,true]);
ok(await scalar(`select display_label='Live park' from ops_accounts where username='PARK'`),'rehearsal account edits do not edit live account');
await db.exec(`update ops_accounts set display_label='Live changed' where username='OFF'`);
ok(await scalar(`select display_label='Disabled' from rehearsal_ops_accounts where username='OFF'`),'live edits do not propagate after one-time copy');
await db.exec(`update ops_accounts set display_label='Disabled' where username='OFF'`);
const set=await rpc('rehearsal_ops_set_resource_state',[admin,'parking.songrim','available',0,randomUUID(),50]);
ok(set.status==='ok'&&set.resource.version===1,'isolated rehearsal resource mutation succeeds');
const photo=randomUUID(), prayer=randomUUID(), pending=randomUUID();
const submit=async(id,kind)=>rpc('rehearsal_community_v2',['submit',{id,kind,text:'Practice',eventDay:1,tokenHash:token,payloadHash:payload,ipHash:ip}]);
ok((await submit(prayer,'prayer')).status==='pending','prayer submitted');
ok((await rpc('rehearsal_community_v2',['moderate',{id:prayer,session:admin,decision:'approved',expectedVersion:0}])).status==='approved','prayer moderated');
ok((await rpc('rehearsal_community_v2',['delete',{id:prayer,tokenHash:token}])).status==='deleted','owner deletion works');
await submit(photo,'photo');await rpc('rehearsal_community_v2',['finish',{id:photo,tokenHash:token,payloadHash:payload}]);
ok((await rpc('rehearsal_community_v2',['moderate',{id:photo,session:admin,decision:'approved',expectedVersion:0}])).status==='approved','photo finish and moderation work');
await submit(pending,'photo');
await deny(()=>rpc('rehearsal_ops_reset_rehearsal',[park]),'parking role denied reset');
await deny(()=>rpc('rehearsal_ops_reset_rehearsal',[liveSession]),'live session denied rehearsal reset');
await deny(()=>rpc('rehearsal_community_v2',['moderate',{id:photo,session:park,decision:'deleted',expectedVersion:1}]),'non-admin denied moderation');
const beforeAccounts=await rows(`select * from rehearsal_ops_accounts order by username`),beforeSessions=await rows(`select * from rehearsal_ops_sessions order by id`);
const beforeVersions=await rows(`select id,version from rehearsal_ops_resources order by id`);
const beforeItems=await rows(`select * from rehearsal_community_v2_items order by id`);
ok(JSON.stringify(await rpc('rehearsal_ops_reset_rehearsal',[admin]))==='{"reset":true}','reset returns only reset true, no private paths');
assert.deepEqual(await rows(`select * from rehearsal_ops_accounts order by username`),beforeAccounts);assert.deepEqual(await rows(`select * from rehearsal_ops_sessions order by id`),beforeSessions);ok(true,'reset preserves accounts and sessions');
const afterVersions=await rows(`select id,version from rehearsal_ops_resources order by id`);
ok(afterVersions.every((r,i)=>r.version===beforeVersions[i].version+1),'ALL resource versions increase on reset');
ok(await scalar(`select bool_and(state='checking' and occupancy_percent is null and updated_at is null and last_closed_at is null and last_full_at is null) from rehearsal_ops_resources`),'reset clears only rehearsal resource status/occupancy/timestamps');
const afterItems=await rows(`select * from rehearsal_community_v2_items order by id`);
ok(afterItems.every((r,i)=>r.status==='deleted'&&r.text===''&&r.event_day===null&&!r.ready&&r.version===beforeItems[i].version+1&&r.path===beforeItems[i].path&&r.token_hash===beforeItems[i].token_hash&&r.payload_hash===beforeItems[i].payload_hash),'reset increments and preserves all tombstones including in-flight upload paths');
for(const t of ['rehearsal_ops_history','rehearsal_ops_request_receipts','rehearsal_community_v2_rates','rehearsal_community_v2_audit'])ok(await scalar(`select count(*) from ${t}`)==0,`${t} cleared`);
ok((await rpc('rehearsal_ops_set_resource_state',[admin,'parking.songrim','full',1,randomUUID(),100])).status==='conflict','stale browser resource write conflicts after reset');
ok((await rpc('rehearsal_community_v2',['moderate',{id:photo,session:admin,decision:'approved',expectedVersion:1}])).status==='conflict','stale community moderation conflicts');
const late=await rpc('rehearsal_community_v2',['finish',{id:pending,tokenHash:token,payloadHash:payload}]);
ok(late.status==='deleted'&&late.cleanupPath===pending+'.png','late in-flight upload cannot resurrect and returns cleanup receipt');
const candidates=await rpc('rehearsal_community_v2',['cleanupCandidates',{}]);
ok(candidates.items.some(i=>i.id===pending)&&candidates.items.some(i=>i.id===photo),'existing cleanup discovers reset photo tombstones');
await rpc('rehearsal_community_v2',['cleanupComplete',{id:pending,path:pending+'.png'}]);
ok((await rpc('rehearsal_community_v2',['cleanupCandidates',{}])).items.some(i=>i.id===pending),'cleanup completion retains tombstone for future sweeps');
for(const role of ['anon','authenticated']){await db.exec(`set role ${role}`);await deny(()=>rpc('rehearsal_ops_reset_rehearsal',[admin]),`${role} cannot execute reset`);await deny(()=>rows('select * from rehearsal_ops_accounts'),`${role} cannot read private account table`);await db.exec('reset role');}
await db.exec('set role service_role');ok((await rpc('rehearsal_ops_reset_rehearsal',[admin])).reset,'service role can execute authorized reset');await db.exec('reset role');
await db.exec(`update rehearsal_ops_accounts set active=false where username='ADMIN'`);await deny(()=>rpc('rehearsal_ops_reset_rehearsal',[admin]),'reset revalidates deactivated account');await db.exec(`update rehearsal_ops_accounts set active=true,credential_version=credential_version+1 where username='ADMIN'`);await deny(()=>rpc('rehearsal_ops_reset_rehearsal',[admin]),'reset revalidates credential version');
const procs=await rows(`select p.proname,p.prosrc,p.prosecdef,p.proconfig,l.lanname from pg_proc p join pg_namespace n on n.oid=p.pronamespace join pg_language l on l.oid=p.prolang where n.nspname='public' and (p.proname like 'rehearsal_ops_%' or p.proname='rehearsal_community_v2')`);
for(const p of procs){ok(p.prosecdef&&p.proconfig.includes('search_path=""'),`${p.proname}: security definer + empty search path`);if(p.lanname==='plpgsql'&&p.proname!=='rehearsal_ops_reset_rehearsal')ok(/begin\s+perform pg_catalog.pg_advisory_xact_lock_shared\(pg_catalog.hashtextextended\('rehearsal-global-reset'/.test(p.prosrc),`${p.proname}: global shared lock precedes operation`);}
const permissions=await rows(`select p.proname,has_function_privilege('anon',p.oid,'EXECUTE') as anon,has_function_privilege('authenticated',p.oid,'EXECUTE') as authenticated,has_function_privilege('service_role',p.oid,'EXECUTE') as service from pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.proname like 'rehearsal_%'`);
ok(permissions.every(p=>!p.anon&&!p.authenticated&&p.service),'every rehearsal RPC executable only by service_role (not browser roles)');
ok(procs.every(p=>!/(?:public\.)?(?<!rehearsal_)(?:ops_|community_v2)/.test(p.prosrc)), 'final rehearsal functions contain no live table or RPC identifiers');
const writer=procs.find(p=>p.proname==='rehearsal_ops_set_resource_state').prosrc;
ok(writer.includes("hashtextextended('rehearsal-request:' || p_request_id::text, 0)"),'raw request-ID locks use unique rehearsal namespace');
ok(procs.every(p=>!p.prosrc.includes("'ops-account:")&&!p.prosrc.includes("'community:")),'account and community advisory locks do not overlap live keys');
ok(await scalar(`select bool_and(relrowsecurity) from pg_class where relnamespace='public'::regnamespace and relkind='r' and relname like 'rehearsal_%'`),'RLS enabled on every rehearsal table');
const rehearsed=await rows('select * from rehearsal_ops_resources order by id');
await deny(()=>db.exec(migration),'second migration run fails at preflight');await db.exec('rollback');assert.deepEqual(await rows('select * from rehearsal_ops_resources order by id'),rehearsed);ok(true,'second migration run changes nothing');
assert.deepEqual(await liveSnapshot(),sentinel);ok(true,'ALL live table/function/bucket/object sentinels unchanged after full exercise');
await db.close();console.log(`\n${checks} checks passed. PGlite executes actual 002..009; no deployed database touched.`);
